spring:
  application:
    name: GreetingsApp
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  file:
    path: logs
    name: application.log